apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: plane-secrets
    namespace: plane
spec:
    secretTemplates:
        - name: plane-secrets
          stringData:
            SECRET_KEY: ENC[AES256_GCM,data:EbVeH9Y1ic4GTZvZIJDIzRDOFTpYfDdZ3FhIec2Ow9uHvB4E+e5eeJfpPNRbo68CmA9WuPM+qkUGVWbSTcN0Rw==,iv:AYmewUj1zvKRvDSp4GHdqhj53py91/PftsK8ih4Np04=,tag:8TmsMRrzzIsxYpATzIQRIw==,type:str]
            AES_SECRET_KEY: ENC[AES256_GCM,data:CBkr9d0WFxi9a3x87xAO2tP0fU5dNx18tvBNYIg3AVO05P7EJOfpij/asGgHa87fTVJPa1Yx9sYqBWo4Kbfk5A==,iv:uzm+mUQn3c7DY0hRYasrSSv5w1BUKQNMiIpVFbvzf6E=,tag:AwiCfR0gWxjqQMv5bGVU2A==,type:str]
            LIVE_SERVER_SECRET_KEY: ENC[AES256_GCM,data:qHOIuvKbukCEBkaNwo8m0sT20THupmHsLmT/UPEdYJje+CWkLyrF9iMPyrImRSefmDhPFbuZhpDK3BwJ5fIGkA==,iv:psQQEd9efWE6IWIlJ+UCWz9aUyrFD7pKI9/GwbqJHZ8=,tag:+XrUSN5DqQxKw0p6vvia1A==,type:str]
            PI_INTERNAL_SECRET: ENC[AES256_GCM,data:dszo0oKwdbShY4A4TvQnJZ5z3s9dM6qL4bj8jiFygQDS7POb61fUuLRitryqRUzjpu/3TKJxUttxImoNKfK7dg==,iv:/HZKe8t8IfOcz64/nw2U3WQNakewpQ+9urphI9KYKsI=,tag:jICPhhPa3EMVPoDVGIKSxw==,type:str]
            REDIS_URL: ENC[AES256_GCM,data:04y3glAu9iqL58FAPd/aC7GdUdjycfsDTQBC2UHrMssDBvxlB9nNL9pCi/EaMB0hLQ==,iv:/WIRZyxol0zX+rCbWolj2UjBUUWYISm/6cy6v8sXVkQ=,tag:dJ82HMb/NbwR7Kk6Rj4plA==,type:str]
            DATABASE_URL: ENC[AES256_GCM,data:R0I9zHhiyxO8/7I+mLOPpWq8y0xin77Z2Or4iNwf4YI7Vm4z0hyt/QQr3sq7ew+v84Gh+27pi4XnKG6/4+PZzB7bfCp6WkVgB6iq+eIiRiPAwEXjqD4hXG1GsOwdBsG4sTZ32bpRN3tPppMz8EWRiu4haREAhhW790OqLw==,iv:zUDeAzw9WkZ/y33Aw0wHdWZKZWW047psumcqZ2qK40w=,tag:D+DZC9Pd55KHQMY1KBpm+Q==,type:str]
            AMQP_URL: ENC[AES256_GCM,data:a5tVlZmfjzfJLREuUSnUtzvO2glaz4FVIcRrbXzc+qRF9TMFJ/O6DsumwfvJJGDfMwutn5O8461mDg32RLqAnoGzDQl8aX3xBYLvi1ejLw4CDl3/c48FX55MTUrg8YDr1Ripf8SuNxxubtLDpBs7BJpClhl+,iv:vQHnAebY2qDJM5MHSqGUTbrtEUiQfaRgXEK8HsgRLoA=,tag:GU4aLC2xtsU6mDIWWd373Q==,type:str]
            FILE_SIZE_LIMIT: ENC[AES256_GCM,data:vIUmYtfi0yM=,iv:TIy4rb8c7Yx2L1RDxe3qQDMO9Azx6BjqZ9uvbeatYHU=,tag:ve1/36QpxGLMLixBoXI6Sw==,type:str]
            AWS_S3_BUCKET_NAME: ENC[AES256_GCM,data:nZn2Gqw3VA==,iv:JZhkMBo8Kh6YoB5dG47W5ty3eMP/A7l1pj7z6rrjNZc=,tag:OA5yQWV3bpG7lawNg7qWfg==,type:str]
            STORAGE_PROVIDER: ENC[AES256_GCM,data:6hU=,iv:7c0W1UJw+9/zd9VJXwUq+qrSE2dX34/R5P+mtB5XlJc=,tag:H5r54qUIXuHNSAqNSKUpgg==,type:str]
            USE_MINIO: ENC[AES256_GCM,data:Kg==,iv:yPDDUzkbC8GSBvTzKj309yq96o+c6EvDkEMnu8XjBhw=,tag:MvKUjSNkez4C8VNaZ2Cf1Q==,type:str]
            MINIO_ROOT_USER: ENC[AES256_GCM,data:FRzD7xE=,iv:nbOM08+gx2QvFs+dnTw1DEaC+AMInvKi1z1YfogqpGo=,tag:6axauZma6fZpkdsmaTpryw==,type:str]
            MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:KdjD08iWtuKfEA/yURmCjiYpeXJnAK2JkSU2o9DyRKxbb70x93fqtegzFQaZw891sVGijQ4N/73QYS5h7oV/bA==,iv:gnR37YZUlqsWqQHkgRWqqZ8CDbTeCug7s6mMjm7j6VQ=,tag:kEOkkEeUC1yoHXXAuJiY+A==,type:str]
            AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uegN8EU=,iv:iDZvnNfawKlXrrFOiBe5lXelU/rzitqfxS/WEJtxlyk=,tag:1JNJKqiztt1FtZO+rDoaag==,type:str]
            AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:UtfopQgN07DKVNsMuM2yKDLIZRqGmae65M9eiK9rRiwifc/zEWkiN6hmGXbXs06OY97rjpiSzPDKSme8mQQxsg==,iv:1XaVbiZgnWc7j4R9JSBH53uktiER+g9/zPflPzSBhy4=,tag:EnSjgmNtwUL86S5/064rKQ==,type:str]
            AWS_S3_ENDPOINT_URL: ENC[AES256_GCM,data:fhunYOlafLVgfwV0NLg45Fy6hSZd2pz4Cm+QqpgAe1fvSOHVxQnH0X4RpQ3nC8M=,iv:tgUHUYMk6ky/4XhkQsogOp5LDWscMX5bvV9v+RRBdrc=,tag:uKvUViVLeJcVac0eaIrkeg==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:OlfuTys=,iv:xN/5RDinAf1ZH8ez+PYv5C+Dh37ql5qWsFD24WSqetw=,tag:qjTEyg16YvZiBqEzh1oQZw==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:i1WM5CUbxtwPvoahDF2NOkhLf2tCE+Cf9QzygBdLbJwaLTkTexIixHYsJyBtVW1jtAlhwCdUj5R3iGiA+05Zww==,iv:vI/rJl5GNaIJsrAAufcplBnR2p0VQK3qKgFS6E1I5VE=,tag:pv00D2doH1kpi5Wiha086g==,type:str]
            POSTGRES_DB: ENC[AES256_GCM,data:p9lna9U=,iv:j6UwcMKQu2b/fof19VYN/rFXwnSuazwNMFWjKDl/Hqc=,tag:wFK7tWxT8bpGAGEF6XqM6A==,type:str]
            RABBITMQ_DEFAULT_USER: ENC[AES256_GCM,data:mRWVNGE=,iv:dWVg7tgn+Mw6thfR+uHeUoIrvzgQKSY4jWcBI077NYw=,tag:8E8rk1KLVjxl+h7cqtfXHQ==,type:str]
            RABBITMQ_DEFAULT_PASS: ENC[AES256_GCM,data:m7ZSARudNdm5PYprMqYVx9EfeeFG0ztczVObbSkEzkCLIu0nrlR36SBypMCaoK+I20oN57vHOE0Y/ccr1q/E6w==,iv:gnyTYPMCCpO5j5CO/xCoQkkJgm8yWa3A4GLXEv01nps=,tag:P0jJPHU4ht1CwpPlcZT9tw==,type:str]
            OPENSEARCH_ENABLED: ENC[AES256_GCM,data:yg==,iv:Rd0YqQ+9wad/HxAgAGI2Hq9qXur/IBHoPhysmgxtwII=,tag:y7m+vaUqQG6WfT7B12Ho5g==,type:str]
            OPENSEARCH_URL: ""
            OPENSEARCH_USERNAME: ""
            OPENSEARCH_PASSWORD: ""
            OPENSEARCH_INDEX_PREFIX: ""
            OPENSEARCH_EMBEDDING_DIMENSION: ENC[AES256_GCM,data:KDvhog==,iv:RCqYhfJSbWhotf9hlLt6N72zhmJJdvjfoX6nXbsj73c=,tag:3k2uUqvPA0GNK31Jl86tBw==,type:str]
            SILO_HMAC_SECRET_KEY: ENC[AES256_GCM,data:qUqc/Z8l6y4wf6s122IDt/YccHjFBGIfuxM+FOiHHvOiGWXqjxamov6ygcvu6bnPLLc+WF4cQAxh+MPYrow1SQ==,iv:QyRFDcWkYDH8G9MtyeaOSo3pEzFmd40NSW69BX4el5Y=,tag:ZMextuAUOjcwvhV09DNO0w==,type:str]
            CURSOR_WEBHOOK_SECRET: ENC[AES256_GCM,data:vT8SLbv8trgQbUG65lye18XtwoSj+c3/cfNu61xXTjgAnGlRkTyZEuDN6Tu34f9kZ7sCEDZxEOCAhTy1z6C33w==,iv:N9LdEV8Pd+QP75g3puEQImZzT8z1Von2+oEoodLJzGY=,tag:pUwLkzRwZ4CWBwdpmxWGFg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYURKTElpcEFWcUhVSU5i
            YlJpRjZ5SFlTdTY5Y3Z5cTNjT2MvZFRDZmlRCkdmeENZd0RNbUdqazFhZVM5SU5O
            VGlyVjVQZEFZQVd6eHh2WlpEMm1ud00KLS0tIDBSZmExV2NoTElLRmk4YzJFb3pW
            Z0FJcjJiODJSdVIwbjl2T2NiQytETVkKYIa373cBF4oIif9AwUwQbn/t3ycYFDbA
            Nq0+gRo54RSv5sXmtHENTG9brT8MX/1s0K09HvEj/eIp51LSkPULug==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-06T21:50:05Z"
    mac: ENC[AES256_GCM,data:WHaFvRyB+gZuunEjhYOE91w2Zbf+vUD/GtlXdKTXFQHt28IEMYZZ7c2vbSMNt/N2oSE4KeSS5Q6hjM4Yf6d9HHWwrQZEgLeqsclE0zZamNbuNiQ4YJg30/Q3rL7ofIq0GuwX4Gyp0JhgKF22T2p/ypXIxhw6TfCJe9q/RYLAYZk=,iv:8b7I0U5OY15nGROnq7X8+sBDIp+2AsJ8pY7hNX/RiGI=,tag:VcQhNKz294A3HwPu9IwknA==,type:str]
    version: 3.13.3
