apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: cloudflared-credentials-sops
    namespace: cloudflared
spec:
    secretTemplates:
        - name: cloudflared-credentials
          stringData:
            credentials.json: ENC[AES256_GCM,data:D8CUnj5y94NM0wxoWZvpimz/hR6GeBGycn0zVpOSsfrBsWg5OREEXmW4LNXhOXiVOSUpRjUXXbOdO1tYBfDtfRiOwruEr3qOerrrw59MJlcZ24MPV7mKjfrUee+rgZa1EMFWFNvAWGxiyzHj6VSnh6hKEm/Rz/Aux9OGnh1jjSN+ABre5TFL5kzBTcwtuh84474p5fjN19Hw6JWbiHcjDildRZbmfapDsh+w7R+Z5Mw=,iv:hShb/sHX6RJJ2XNKCJnBaCaVm/vHRBM+sX4d/E+MoBA=,tag:TRBP5ZH9qrePEWcuH/Lt/g==,type:str]
            config.yaml: ENC[AES256_GCM,data:u7xBs44gHLHqGdlpybxGq7jqOE8q+GtRWm6Yf2dVMI10rar/LTwxi5MUigi6N9TnAo6Jz5VXQ/g8cU257qTKpXWmcs5Dmb2LL97BjVWgQccq533t6YSvW3PsMMO7W8V3fa7z5CmeFR6eOdjERDdzQ0wLDgzvutBSPJRQqeW9xxYj2wZgHB57wksJq8CfajVeE4WsN2De8142gZGb1PdcC91/auaiaCzVQYYWRAbrIcXJVFP18sCq/k2ve34sW/lRuP2sRx9c+jcy5tUBEa70JAn4GpCqj5WWk4wGc3ImjxoNPlZDEDRU3jWzmphuMZseWFsW,iv:U64/kLjr1SBYHWs+LCcls37sx9ufOeGkDs5SUQRijbA=,tag:wI6MWVXtliPr/7bJ90BCJA==,type:str]
sops:
    age:
        - recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MlViREt3UkhycE5Ka29R
            T21xb2hPVDZHVSsxM1lDajlsYVUvOFpwSGdJCm1USTJ2ek1hanZnNE9oOHNpZVRJ
            bDdpcW4rMlV5eGY5TzZwRzV6clNFT3cKLS0tIDIyZHYrYUxKMENqYVpQK281R3JS
            M1ZCYVhEVDUrNjdERTB0dkdZRjdmNVkKQlTNwy+NT/3CmECkN881W/tMcMaLRuJO
            dwQgycChvzPl9N+t51eXGY5EUiv+xAfncDI0rKWGIBlZCpAu9MpsIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-26T22:05:02Z"
    mac: ENC[AES256_GCM,data:A+ay3TGrUsD70RRRltCmrq553MLHLZ7/nG8mORiuHQSE1DoZQXUmF0rd4Okmw4p1bPrZ5UjEo8HLL5m+GN8d+GAv2HBrhgriJE5ES5MrvYIWBB8t43Sz/GuVwg6Nun5uJgoSJ0IJoZcC8SnHBRFnCm+o8Ahg5/gzCUNf6CvQem4=,iv:3wbEaCGZbZ1kHsYVVUwNa2fKw5QpABwu0qcYBYYmPls=,tag:AeZbtUFfUoEXDrwgdzhwSw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
