apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: alertmanager-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: alertmanager-config
          stringData:
            alertmanager.yaml: ENC[AES256_GCM,data:u2nbhA73nifLoycJxZPmNMQsPI8Frdnm3rn32OXt3kXif5qk2xJetCL2XAWYNopRbFU2wrMyOaGYf0VXSvV/CZX/kWOSGCcMT0UiJWwW/G2RunXgPNJtGSrFvPCuPH+Fqn5SzT8DpMCV3dgg/d49Q780maDKCOuqNY9qca7PD/3WqxLz1mlPav9fxhUjw5arFyvVSqSLQfYG0oob9muaWFvHZs5MVC3P37NEhhygIvhoy0+dPAFBDSD6m5p1VWCocvSxoER4BgdCL9KamKDKNawdFsBZyOEuMXn3ASLvTA8rr8eiAHg8E5kkpP03FytezadMny2ywnlNNij92RRHEyVdQiQf9MVg9w6S8Ze0t4Zt6gDXz6lNRIMBZSwoXHrQuk8C/4Mrmd6QqpDOBuSCE02XY80LUGKaDY3TbeFnGRk4z0mg8yD51VY44lYemYldiLX3sWTnZUy9cMyHwL0g7vHgz71mBi/kPZBu3dj5mbmWPGa7xWGUggP9ErWs/8kjjgj+Mb8nIo7/hPZsVt1r96DJgoZEN3o92c3kmAVxrNq4QQgy0BXz5oDvZPfs4P6do1KeVeyforQcNFPouou4vZNaHr8qaJWbr+tvqR2g+chH1FHitSPbbq3/pIS1ngbxQI8QI9EikrHoAPGtjfiqo8+DCjcIwuyms3PzxO8CHeaiCU0lNJie3JjoErS45OAca0Bk0kN15szMHyFonmiwVztKy29S9yfCuaRvxISrWNvhwC3HA7FnqqFIE+WUQxWu5iFszykPwja8xvvoxBHB0OujVWG7icAeuD6v5YUVg6gnu0a6nGIuZ6RffHf/KoLveb7MsBWqJU7DUQjUkThIkvTp5Rv1jYQMkboHe6CGZEsbN05vXbhQw6m5vUustvkayCxZxIAzGu5vCO+qpZg6kAFKSHs4lErGQc4ARwG7kHJY9/LCeeRk621R2LQ10aZ6gMmxdZdNet3GkGEAVX42uCFPmCsw24IXUHJnauxYjrSTkSc1m/qUiZx5TdlE62gbmDRENZk7TxIHU421o/WakUHl009br4zE1+j3pm+fH414sE/UTtNysyJe1zmw690qafK13x8eOV38yd7fKdGWT4d3U4C/BUK82vmrdZTfsoWnrhCmrAw+sp8RiNxXSOY1tJZUwQBKmUmZiafFsevPrJNCD+e0+GZA2t+I2z7rlcpYkGB0PerkSou8N6nXleZK7dUgVFmgQ1oyGqTP1ElR6UM62l3Ka+vUueJaWFWUhno/pKiEGkhU2aeKOkzYLCh/tIdnfOsJlw8OfuUjtmeZ5Z9iy8lMdKsi7QAezQXxALVzaRfGWMTFZHwzH0j/bjTNU5AqZPKVSHg4xnyq/P+raLzk9ZpbiSCgGqNr9FgAEw8xD7Ct8M8YlNWRip0rDU7ZtwHNUl04jbPBcEmaRYdKbnr/9qAP/p02CCTP9okfPZubmg9LVjQiMmHV20JvAeT3DEislID2A+i7zulpNxpelj4FhOs8KDkTjNpV7oG9e7vjLubY2oohjVZ1AFhXGmeypj+BCHGOjrQL0cIFyB5dfpO11szySzhJ3LUfLOlxEYd+QPKxTCE7,iv:tCXI8N12yEl5+uvU5XwqhtZFd7StUHvw/ngm2VMPjAo=,tag:plCO0VTfQ9q/OEmXq8lHzg==,type:str]
            telegram-bot-token: ENC[AES256_GCM,data:MZEaajXGr+S8yKQoPD6LTdKR3IMD+g13JJfvkcgVQ5I8SzvES6szmCrg21xy7w==,iv:7Na1d4tjsIFhfKCxd8z3OO5Mp0ZroPbTkd3n+Hg8BIE=,tag:XiCnpJG2VpwyKHepHlJriw==,type:str]
            healthchecks-url: ENC[AES256_GCM,data:TDzcJSN8JnHlAJgm9TM4MTtavgmnjwomK9j5xZLKihZsVJ8tF6sLr5nM77+5+ynhDq3gj6V0RUw=,iv:VGr8inM4CG9G0k3Y1DuKYDn+bIa+YsWTa09ZyPYWEnA=,tag:Pt+Dr1s+S1PywUWZhKZVYg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QWpvRFpJUTdxckZUTi9Z
            UGEvTUM2TzloaER5NTVZemFlbTdvRDVqZlJ3CmlpYzVwaDEwOGNwRndzQldFV0Fr
            S2N5ZWdjM3d1eUZHSzdxcEJJUlFrTEUKLS0tIDNhSmwrS2FISnZjdzZlNmYxa3U2
            ZGt2VEdEOUd1L3M2UG11L3BXUUczT3cKlO94PUmD0mpn4UQMe9YKcKSl3iy4c/oP
            G7p7PFxznH2CnwtGA+tu3cCoU+CMtybUOyBQzlYkuWUiyj6nPZXhNQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-20T19:31:07Z"
    mac: ENC[AES256_GCM,data:jZkrAEIRkQxGCzJjDW7RhajuM4lpa8FQLa34oXfZq/lJEf382DabHIQp5XpeOeLYtf6x+55WcaPXdPbH/Jw9dBLTwyEdx+uusvNa+eHADGgY0Vl3qGzLFXJjEAg5+LZB/pXSoloYpVQqYRY6KXD7IC42fTXCnI/BhM5sNRtsC+U=,iv:bGU36gO/hG5rU1YElF3pbH9UaQf5+9cvMOFXbyi87t4=,tag:I+PduJtlPxAPHET9EPRSIg==,type:str]
    version: 3.13.3
