apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: monitoring-secrets
    namespace: monitoring
spec:
    secretTemplates:
        - name: grafana-admin
          stringData:
            admin-user: ENC[AES256_GCM,data:8wcN1VQ=,iv:vcj6MwY0ivIZ81IzsOYWNVzUP+dlkkwkwUM4OWn5yDE=,tag:BgacZPf5Zy7XTCZklHws8A==,type:str]
            admin-password: ENC[AES256_GCM,data:mOZn1BnbJ7QMNdPHVLQny4Uj/hzAmwtusQ0UFokjv6dR92b19B5W1g==,iv:hJJJ60Mg0ZFKZYUnCoiGR4j6VruOLWkhrQRs5Jiaxfc=,tag:rKmvBgpt5i8Dk9VOvoM0Pw==,type:str]
sops:
    age:
        - recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWWlVQNzBhWFFwaVJkNWlD
            UnpKZTdGTDg2RVovRHRCejBWRTExMTNXQlhBCkRkU0hSZ2o0WE10YXo0TklyYXFG
            ajg0NDRmRTR4Y2JvakdyRkRyT3RENUUKLS0tIG5YRWtET1RGeWlPUVhBdlJwd1h6
            WkRrcWh6UXVlU1U0ZGlZSDVxR3E0S3MKfpMZ2wGyUb9zAv9s+N1oes3oW/l3fdxp
            5v4WnP9lU/Jew6ouqhLYyGvwkbcgfh7aoULUfF/i/qavv7oyJVZ+AA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-25T21:11:43Z"
    mac: ENC[AES256_GCM,data:U2Rqoem4bx7UEgQlql7bNSnVNmWWKvZuuHQM58V/D4PvU0HbUA7rM820ELfTMThnJyJnbRB2GBwDrYR1nxc8PBhzeeWFbSp2ZxQx8Y0ZrjHONeGoKIpfS3vnAlHKonzUlUhWTqKQxZF6cQshYZrlC6azG0wYVtPXEu4wiiOVVeU=,iv:D4cFYhuNbHDk0TneizOtcEWZJssBLiQRdmIF51qObGA=,tag:+zHD7kva+cZTtO3lFC2WmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
