fullnameOverride: kps
prometheus:
  prometheusSpec:
    retention: 30d
    retentionSize: "18GB"
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 20Gi
    # Scrape any ServiceMonitor / PodMonitor / PrometheusRule in any namespace
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
grafana:
  adminPassword: ""
  persistence:
    enabled: true
    storageClassName: local-path
    size: 5Gi
  defaultDashboardsTimezone: Europe/Warsaw
  grafana.ini:
    server:
      root_url: "http://grafana.k8s.hyperion.internal"
      domain: grafana.k8s.hyperion.internal
    analytics:
      reporting_enabled: false
      check_for_updates: false
alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 2Gi
  config:
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    receivers:
      - name: "null"
nodeExporter:
  enabled: true
kube-state-metrics:
  enabled: true
