apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: livesync-secrets
    namespace: livesync
spec:
    secretTemplates:
        - name: livesync-credentials
          stringData:
            admin-username: ENC[AES256_GCM,data:uCR1lcq9KSQ9zA==,iv:7G5u28OLPT09IjPoEJgU40fUBwcPe9sk8dyQIYsuzpA=,tag:dOOiiMOPsWcgdYu9V4a3qQ==,type:str]
            admin-password: ENC[AES256_GCM,data:QCliT5B1oWvHxcSBnIbijohBFgNTm1CBjy/9jG4AUSU3ibChe5RoDo35hlJChN5G,iv:8aJqdnTpor7KcrEI9iG4gDTMfXuIoiWbQoeySa5ANSo=,tag:80GeVmSs6XizuIfKC4Gjpw==,type:str]
            app-username: ENC[AES256_GCM,data:3toLEB4uURY=,iv:C8N427bsnLHFu1GxVggJNjFX/+ZmPbSDgvmRiJ+C5pk=,tag:Nbo8XZ+ruVM8JoMQW5koIg==,type:str]
            app-password: ENC[AES256_GCM,data:ta+b3EtuQ3XyU908q/6yAgdzsC9ofqtsOB0GiNtnO9UlmYLMIdNMvqTXkIvyR9UF,iv:1lgVV3resrPizc/Cq/SUOPLwiGN4g5uzvyMVRIW7UOY=,tag:4ga+EzOXPxE1i8cvgnez+Q==,type:str]
            e2ee-passphrase: ENC[AES256_GCM,data:4SyUAGD2K0bGFKZdXasR4FcXHBoA1nTWkdeJPHa1pr/5k9h7TohojZR0agMY3nW8M3bJ1D09yQdV0l1fkCHrNw==,iv:i+G8IyIpEFBkJPPW5NQ+AU2C73Ywq2QPVBptJlNZhyo=,tag:c7R37FwV+2x+fS4ouvYNTw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdXE5Y0I0MXBMeUl5a1U3
            SGtnSTE0Zllabkc2R25ML3MramhscGV2cTNNCnZTZGYycDRDNm9ZVVY2Y1Z4TlZy
            OUlzWlVZMDA1RFgvbGZ6c3ZKT1ZJeVUKLS0tIGNxeDdHNDYyUWVDbHM0RnVpNTNT
            QXR3MHdCbGEySzZsbklPUjJYY1BBbncKxXRd8ZWkJgnDE+pQ5atdyuqtc/3mT70D
            ENy2f7r1mtarv1f21nLy0MtCdrh/LZw3vLY4r47ofwDx8nb4j2eQJg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T20:30:22Z"
    mac: ENC[AES256_GCM,data:1ttPil244guu06vVqUtXO0RPG7Vj+F5oJDD0W4bCCQPLvku3+i4OYzojPzyYSWEp4ujHWJFPqaKBbqUHTcADnbK7KSLWCeto6HoKptrWDAKPB1sRE4KdiAyBlPc63R86DnJsgKHKlCT2vRNyqnIJHXjDbcf3l6fXN078T7xnG/g=,iv:mNGi0zk4BSXKKiIvU8wf8JZg0xLu++gvvJ0Z9tPH6m0=,tag:E0wYygYdk81pQWPHxDGEDg==,type:str]
    version: 3.13.3
