apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-routes
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dgabka/homelab-k8s.git
    targetRevision: HEAD
    path: apps/argocd-routes/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
