apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-repos
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/dgabka/homelab-k8s.git
    targetRevision: HEAD
    path: apps/argocd-repos/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
