apiVersion: v1
kind: Service
metadata:
  name: traefik
  namespace: traefik
spec:
  type: LoadBalancer
  selector:
    app: traefik
  ports:
    - name: web
      port: 8800
      targetPort: web
      protocol: TCP
    - name: websecure
      port: 8443
      targetPort: websecure
      protocol: TCP
