apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: gitea-secrets
    namespace: gitea
spec:
    secretTemplates:
        - name: gitea-admin
          stringData:
            GITEA_ADMIN_USER: ENC[AES256_GCM,data:uZP+9/Nw,iv:Bg6WJQBp/rPolgw4LKE8fGa7IXNx3dAnPhFohBaGLzQ=,tag:xt8srtK6oDtBXd09/Y+HWQ==,type:str]
            GITEA_ADMIN_PASSWORD: ENC[AES256_GCM,data:bMfPdlCmMYy5VG8CCChUZtumxKr5Gdt+sFscIo1ELMM=,iv:wbxqZ+EPP1JJDTwpJLoF/Yo5hksVcGI5tuR61Su2Qls=,tag:mNZjcZ5/7fO7HsLNICzmAw==,type:str]
            GITEA_ADMIN_EMAIL: ENC[AES256_GCM,data:xcSel0nfDsOb+POln1jcf3hpzQ==,iv:cGBQV8NHqkpbYZV8kCKezSXVSQyI3fyhUTsuBKtl0Xg=,tag:zjzZoOuA3qmX9xwzyVlCeg==,type:str]
        - name: gitea-config
          stringData:
            GITEA__security__SECRET_KEY: ENC[AES256_GCM,data:ZZ8f/DDU2A0HsE0X1igQL0OlgoWxxDvtjsftKZ/xvpFCQTjlZm3LBbHvGwA=,iv:tpdLN9jbDZEE7cDEw+MrH+dgZCrbg89v0ecKA82fgOk=,tag:RFkUeZB9rmsauVw35CATQg==,type:str]
            GITEA__security__INTERNAL_TOKEN: ENC[AES256_GCM,data:1TQGn7kdnShKEfc0R2jjpFkxydvrwOQwlmQxmXyn2elaATAs70oKM6nqBIg=,iv:J4H5ewQIHIR+s9+t309HbbVTk91gXT8OxG2kY0pvqzc=,tag:iMz7AurH3AQjrpfSPSxB0w==,type:str]
            GITEA__server__LFS_JWT_SECRET: ENC[AES256_GCM,data:DdUUt5HKi+zCwZvO8uNVtENXfoo8SkSUNttTjb0Tj1+Utgg/FeBthwgQ+gY=,iv:v6uP1UVRpKb0Kz/jtWgWOE/AJ379gJ/+28mlIh6hHRo=,tag:9e2I7pLUnoFNIhm9Fa35yg==,type:str]
            GITEA__oauth2__JWT_SECRET: ENC[AES256_GCM,data:4MYrLEg0TTSf/jzxbtCxTejyO8bv95JYXAlg2jQIfjVHjmzFVr7dLxECTwU=,iv:z/KnIanEiS5CQ/oCcgeoJaNr/ha2DLtrn4ZsqcucvsY=,tag:qmaLJIPVVK7v4+1534Rvcg==,type:str]
sops:
    age:
        - recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjOWFVcWhXb1VJYzMzdnUy
            bCtHQmRJVHljZUxjNHA1ZU9DZDZqL3NMY0NRCkNJQWkvOHdZSjlUUmZESG9ZRHFk
            VjhBbmhmdlF1VG5ENnFhNkZrNHN4a1UKLS0tIGdLektMc0Z5a0NHUlZKaUgyb3ZR
            TGs5c1gwTWNHdC9GcWJqeUc2Q0ZvaEEKD9bQUpwylNhLkmSSbO5Nh28lM9mYNERH
            1Jwk1YMd97cv6hYetUVS+vCQ+8EtRBDZpMTRI5aPhF+4HAUb/QMXOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-09T23:17:08Z"
    mac: ENC[AES256_GCM,data:q7gaX/TFzWnW5oRkAJS3UT+MdFtFihfX16ZHr0cCTQ0K7Zp5gSM29+wfBSAjNlJM/tu0NR9iTQPBxqePWDJJzXC6nRWzzrE7yWiuQi7ubqTeNJM23oxgPCT2Nk556cIsqSlj4LiUQLAMq/Lg/zeOe+hC4phCyY+MeI6jduP+5HY=,iv:s/KXCrNg3zPJiKmzocbzbB1L8LUlUiGejyPJS8U7dqE=,tag:HqRDEfFGhL8oczex22fe9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
