apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 18.9.1
      helm:
        releaseName: loki
        valueFiles:
          - $values/apps/logging/loki-values.yaml
    - repoURL: https://grafana.github.io/helm-charts
      chart: alloy
      targetRevision: 1.11.1
      helm:
        releaseName: alloy
        valueFiles:
          - $values/apps/logging/alloy-values.yaml
    - repoURL: https://github.com/dgabka/homelab-k8s.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
