apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: paperless-secrets
    namespace: paperless
spec:
    secretTemplates:
        - name: paperless-postgres
          stringData:
            POSTGRES_DB: ENC[AES256_GCM,data:bHSjsa7YF3Yy,iv:h+flOnVdRXrGGkqR60Y1RjLpkB+3GKwBBfxwwL/l1OY=,tag:HRjFtoKvcrNVHDZ5e2GkIQ==,type:str]
            POSTGRES_USER: ENC[AES256_GCM,data:sK9nCJFLdfwp,iv:N435NByPJHGsqlL0AFn5amUqjDDb5kbGUwCbrF3ssKg=,tag:w+LA+qX0EY6bQZXcRdoaig==,type:str]
            POSTGRES_PASSWORD: ENC[AES256_GCM,data:e3e1Xk4g3xphOgIQ4kHMxhWIRYomR17PNmYs+dIO3D+ByjYXYV3oMD/lNwU=,iv:mBFabZRaAR51wZSuXc2NwA4AkDfS9A27809NDqUSt6g=,tag:czpO8+0zcrDyOaIsF9so7g==,type:str]
        - name: paperless-app
          stringData:
            PAPERLESS_DBPASS: ENC[AES256_GCM,data:cDr/t4FH5S8Tnfn/RI/vTOxTl0kJlsvA8tVBLtZrnfqAWEbaNUpe0OCfr/c=,iv:N0XzNFivMN+T5Nwug5y9TJlEYE0foNAplqZfAqgPED8=,tag:K62rwFillB0xq7L4HjZnWQ==,type:str]
            PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:Xil9RUpHP/mOi0PbBSjl//r8Q3IA1lOnXFJDoxKfgzFAa1MSbj+XDrtGIU57XIHROjRy0oP8wHX8XT0xrI9Rs6BIPnm49CdGUxQEH1kAtFHRD1uV8XobNw==,iv:OqxiYQFdGnYK4+KXZuWxHU9/giaynlXazWY6ITnAMTo=,tag:sYb5VUF73sBgz/NZDSzPPQ==,type:str]
            PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:pUtEmgd+,iv:E1MN+OMawvXRamcEgGnUNmlmDO0EO2MQi/nyzeOLYpg=,tag:0aioscJiVT1D3Vw6cLHd3g==,type:str]
            PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:6pm8NK0cXw8=,iv:TFgr72eKmNvFHsWLFLyZIcC5iGS1hHGe+a/CyWpJF+M=,tag:RANQxW//MdliQKs9P2SfmA==,type:str]
sops:
    age:
        - recipient: age1qxy5wve7cm5v2wev79de5uc4ceqhy9axakqy6szhwq3prvp66cksahtu5z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFKzBxNjlaZkpESUpmSEhm
            Y09WTmw3OC80b0U1K005WCsyeUVNeWd4WFNzCjV3OTlqMVlpUUh0bVNlMlZWaWdw
            bWNxc05vc2YwdzBUemw5Wmo0RldNRkUKLS0tIEEva0RQNk9kSVFVNHAxYTZlN1NF
            RHhIS3hoM29qNnJXMVJhcFVBK0hlLzgKP7OL+mhH16udeOfvEGSD3DsxZ127vqCh
            iqj2XbRp/JA1/T0MZ1oSvMMrTmn0mdMTejZ5KXgyldqyrJis0MNi4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-07T22:14:33Z"
    mac: ENC[AES256_GCM,data:XkoRWO0GOqq2W82zKDIRvHQ4LDuMqQ2WNuf2mKVqDfJXkaJaS9LAtZkq+CKe48drb3GIdKTw3SW+Eo7SvLsVrVMs5XXdedj3jkQCDFCt5F9LvimMMPX2DMW0qc21GPBxqt2A30hVzYwaVX4TngFaCIVb+B77rVnImiyNh4c4AO4=,iv:CxtgyFl3cX6bacvWoEfLQhkvJyJpch5J0YvuG5O7YnM=,tag:J4WD4u9gd3LJekG7/LaVjQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
